// Copyright 2023 JoyLee (@itarze)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* USB */
#define MANUFACTURER "EWEADN"
#define PRODUCT "Smart875"
#define VENDOR_ID 0x414B
#define PRODUCT_ID 0x6390
#define DEVICE_VER 0x0001
#define FORCE_NKRO
#define USB_SUSPEND_WAKEUP_DELAY 1000

/* Multimode */
#ifdef MULTIMODE_ENABLE

#    define MM_BT_DEF_PIN    C13          // 三挡模式切换蓝牙引脚
#    define MM_2G4_DEF_PIN   C14          // 三挡模式切换2.4G引脚
#    define MM_BT_PIN_STATE  0, 1
#    define MM_2G4_PIN_STATE 1, 0
#    define MM_USB_PIN_STATE 1, 1

/* 非量产版
// #    define MM_2G4_PIN_STATE 1, 1
// #    define MM_USB_PIN_STATE 1, 0
*/

#    define MM_BAT_CABLE_PIN A15

#    define IM_RGB_BAT_REQ_CLOSE_ALL

// #    define LP_UART_WAKEUP

#    define MM_BT1_NAME "Smart875 BT1"
#    define MM_BT2_NAME "Smart875 BT2"
#    define MM_BT3_NAME "Smart875 BT3"
#    define MM_BT4_NAME "Smart875 BT4"
#    define MM_BT5_NAME "Smart875 BT5"

#    define MM_DONGLE_PRODUCT PRODUCT " 2.4G" // 2.4G模式下名字


// USB模式未插入USB时跟随无线模式一致，进行超时休眠
#    define MM_USB_AUTO_SLEEP_DISABLE // 关闭USB插入时休眠，usb有供电的时候不休眠

// 键盘无操作超时休眠时间
#    define MM_SLEEP_TIMEOUT (5 * 60000) // 5 min
// 键盘回连超时时间
#    define IM_MM_LBACK_TIMEOUT (30 * 1000)
// 键盘配对超时时间
#    define IM_MM_PAIR_TIMEOUT (30 * 1000)
// 键盘回连或配对成功时，模式指示灯常亮时间
#    define IM_MM_SUCCEED_TIME (2 * 1000)

#    define RGB_DRIVER_EN_PIN B9
#    define RGB_DRIVER_EN_STATE 1

// 用户自定义长按按键数量
#    define IM_LKEY_COUNT 6

// 使用RGB BLINK功能的数量
#    define RGB_MATRIX_BLINK_COUNT 5

// USB模式指示灯和无线模式指示灯一样的效果
#    define IM_MM_USB_TIMES 1 // 0xFF

// 使用一颗RGB灯作为模式指示灯,定义此宏
// #    define IM_MM_RGB_BLINK_INDEX_MIXED 0
// 使用单独RGB灯作为模式指示灯,定义下面宏
#    define IM_MM_RGB_BLINK_INDEX_BT1 30
#    define IM_MM_RGB_BLINK_INDEX_BT2 29
#    define IM_MM_RGB_BLINK_INDEX_BT3 28
// #    define IM_MM_RGB_BLINK_INDEX_BT4 0
// #    define IM_MM_RGB_BLINK_INDEX_BT5 0
#    define IM_MM_RGB_BLINK_INDEX_2G4 27
#    define IM_MM_RGB_BLINK_INDEX_USB 26

// 定义回连时每个模式指示灯颜色
#    define IM_MM_LBACK_COLOR_BT1 RGB_BLUE
#    define IM_MM_LBACK_COLOR_BT2 RGB_BLUE
#    define IM_MM_LBACK_COLOR_BT3 RGB_BLUE
// #    define IM_MM_LBACK_COLOR_BT4 RGB_BLUE
// #    define IM_MM_LBACK_COLOR_BT5 RGB_BLUE
#    define IM_MM_LBACK_COLOR_2G4 RGB_GREEN
#    define IM_MM_LBACK_COLOR_USB RGB_WHITE

// 定义配对时每个模式指示灯颜色
#    define IM_MM_PAIR_COLOR_BT1 RGB_BLUE
#    define IM_MM_PAIR_COLOR_BT2 RGB_BLUE
#    define IM_MM_PAIR_COLOR_BT3 RGB_BLUE
// #    define IM_MM_PAIR_COLOR_BT4 RGB_BLUE
// #    define IM_MM_PAIR_COLOR_BT5 RGB_BLUE
#    define IM_MM_PAIR_COLOR_2G4 RGB_GREEN
#    define IM_MM_PAIR_COLOR_USB RGB_WHITE
#endif

#define RGB_MATRIX_BAT_INDEX_MAP { 30, 29, 28, 27, 26, 25, 24, 23, 22, 21 }

/* UART */
#define SD1_TX_PIN A9
#define SD1_RX_PIN A10

/* Key Matrix */
#define MATRIX_ROWS 6
#define MATRIX_COLS 16

#define MATRIX_ROW_PINS \
    { B3, B6, D2, A1, B10, A4 }
#define MATRIX_COL_PINS \
    { B1, B0, C5, C4, A7, A6, A5, C8, C7, C6, B15, B14, B13, A0, A8, C9 }

/*
D2
#define MATRIX_COL_PINS \
    { B1, B0, C5, C4, A7, A6, A5, C8, C7, C6, B15, B14, B13, B12, A8, C9 }
*/

/* COL2ROW or ROW2COL */
#define DIODE_DIRECTION COL2ROW
#define TAP_CODE_DELAY 10
#define DEBOUNCE 5
#define HOLD_ON_OTHER_KEY_PRESS

#define LP_DIODE_DIRECTION ROW2COL
#define LP_ACTIVE_STATE 1
#define LP_PAL_EVENT_MODE PAL_EVENT_MODE_RISING_EDGE

/* SPI */
#define SPI_DRIVER SPIDM2
#define SPI_SCK_PIN C1
#define SPI_MOSI_PIN C3
#define SPI_MISO_PIN C2

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

/* Flash */
#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C0
#define WEAR_LEVELING_BACKING_SIZE (10 * 1024)
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)
#define FEE_PAGE_COUNT (WEAR_LEVELING_BACKING_SIZE / FEE_PAGE_SIZE)

#define RGBREC_CHANNEL_NUM 4 // 录制灯效数量
#define EECONFIG_CONFINFO_USE_SIZE (4 + 16 + 16) // 用户存储区大小

// 固定，不要动
#define EECONFIG_RGBREC_USE_SIZE (RGBREC_CHANNEL_NUM * MATRIX_ROWS * MATRIX_COLS * 2)
#define EECONFIG_USER_DATA_SIZE (EECONFIG_RGBREC_USE_SIZE + EECONFIG_CONFINFO_USE_SIZE)
#define RGBREC_EECONFIG_ADDR (uint8_t *)(EECONFIG_USER_DATABLOCK)
#define CONFINFO_EECONFIG_ADDR (uint32_t *)((uint32_t)RGBREC_EECONFIG_ADDR + (uint32_t)EECONFIG_RGBREC_USE_SIZE)
#define LOGORGB_EECONFIG_ADDR (uint32_t *)((uint32_t)CONFINFO_EECONFIG_ADDR + EECONFIG_RGBREC_USE_SIZE + 4 + 16)
/* RGB Matrix */
#define RGB_DI_PIN B5
#define WS2812_SPI SPIDQ
#define WS2812_SPI_DIVISOR 24
#define RGB_MATRIX_LED_COUNT (90)
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_SPD_STEP 70
#define RGB_MATRIX_VAL_STEP 70
#define RGB_MATRIX_HUE_STEP 32
#define RGB_MATRIX_STARTUP_MODE 1
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define RGB_TRIGGER_ON_KEYDOWN

// RGB Matrix Animation modes. Explicitly enabled
// For full list of effects, see:
// https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
// #define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
// #define ENABLE_RGB_MATRIX_BAND_SAT
// #define ENABLE_RGB_MATRIX_BAND_VAL
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
// #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
// #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
// #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
// #define ENABLE_RGB_MATRIX_RAINBOW_BEAqqqqqqCON
// #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
// #define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
// #define ENABLE_RGB_MATRIX_PIXEL_RAIN
// #define ENABLE_RGB_MATRIX_PIXEL_FLOW
// #define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
// enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #define ENABLE_RGB_MATRIX_SPLASH
// #define ENABLE_RGB_MATRIX_MULTISPLASH
// #define ENABLE_RGB_MATRIX_SOLID_SPLASH
// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
