// Copyright 2024 Y&R-Biu (@jiaxin96)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* USB */
#define MANUFACTURER "EWEADN"
#define PRODUCT "Smart875"
#define VENDOR_ID 0x414B
#define PRODUCT_ID 0x6390
#define DEVICE_VER 0x0001

#define FORCE_NKRO
#define USB_SUSPEND_WAKEUP_DELAY 1000

#define RGB_MATRIX_TIMEOUT (5 * 60000) // 5 min

#define LPWR_TIMEOUT RGB_MATRIX_TIMEOUT // 无线休眠用时
#define WLS_KEYBOARD_REPORT_KEYS 5 // 无线模式默认按键无冲数量，最大是6

// #define USB_POWER_EN_PIN A14 // 上拉控制
#define LED_POWER_EN_PIN B9 // 灯光电源或者GND控制

/* 充电 */
// #  define BT_CABLE_PIN B8 // 充电接入时为高
// #  define BT_CHARGE_PIN B9 // 充电时为低，充满时为高

/* RF */
#  define BT_MODE_SW_PIN C13 // 低电平时
#  define RF_MODE_SW_PIN C14 // 低电平时

/* UART */
#define UART_TX_PIN A9
#define UART_RX_PIN A10

/* SPI Config for spi flash*/
#define SPI_DRIVER SPIDQ
#define SPI_SCK_PIN B3
#define SPI_MOSI_PIN B5
#define SPI_MISO_PIN B4
#define SPI_MOSI_PAL_MODE 5

#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C0
#define WEAR_LEVELING_BACKING_SIZE (2 * 1024)
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)

#define EECONFIG_KB_DATA_SIZE 1

/* COL2ROW or ROW2COL */
#define DIODE_DIRECTION COL2ROW
#define TAP_CODE_DELAY 10
#define DEBOUNCE 5
#define HOLD_ON_OTHER_KEY_PRESS

/* Key Matrix */
#define MATRIX_ROWS 6
#define MATRIX_COLS 16

#define MATRIX_ROW_PINS \
    { B3, B6, D2, A1, B10, A4 }
#define MATRIX_COL_PINS \
    { B1, B0, C5, C4, A7, A6, A5, C8, C7, C6, B15, B14, B13, A0, A8, C9 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 6



/* RGB Matrix */
#define RGB_DI_PIN B5
#define WS2812_SPI SPIDQ
#define WS2812_SPI_DIVISOR 24
#define RGB_MATRIX_LED_COUNT (90)
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_SPD_STEP 70
#define RGB_MATRIX_VAL_STEP 70
#define RGB_MATRIX_HUE_STEP 32
#define RGB_MATRIX_STARTUP_MODE 1
// #define RGB_DISABLE_WHEN_USB_SUSPENDED

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

// RGB Matrix Animation modes. Explicitly enabled
// For full list of effects, see:
// https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
// #define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
// #define ENABLE_RGB_MATRIX_BAND_SAT
// #define ENABLE_RGB_MATRIX_BAND_VAL
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
// #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
// #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
// #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
// #define ENABLE_RGB_MATRIX_RAINBOW_BEAqqqqqqCON
// #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
// #define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
// #define ENABLE_RGB_MATRIX_PIXEL_RAIN
// #define ENABLE_RGB_MATRIX_PIXEL_FLOW
// #define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
// enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #define ENABLE_RGB_MATRIX_SPLASH
// #define ENABLE_RGB_MATRIX_MULTISPLASH
// #define ENABLE_RGB_MATRIX_SOLID_SPLASH
// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
